version: "3.7"
services:
  sample-project-core:
    image: $DOCKER_ORG/$REPO_NAME-core:$REPO_HASH
    build:
      context: ./packages/core
  sample-project-leaf:
    image: $DOCKER_ORG/$REPO_NAME-leaf:$REPO_HASH
    build:
      context: ./packages/leaf
  sample-project-sockets:
    image: $DOCKER_ORG/$REPO_NAME-sockets:$REPO_HASH
    build:
      context: ./packages/sockets
  sample-project-web:
    image: $DOCKER_ORG/$REPO_NAME-frontend:$REPO_HASH
    build:
      context: ./packages/frontend
