apiVersion: system.codezero.io/v1alpha1
kind: DevelopmentProfile
metadata:
  name: teleport-sample-project
spec:
  commands:
    - command: Teleport
      params:
        kind: Deployment
        resourceName: sample-project-core
        namespace: sample-project
